# Using an official PHP image as the base image
FROM php:8.2-apache

# Installing dependencies
RUN apt-get update && \
    apt-get install -y \
        libzip-dev \
        unzip \
        && docker-php-ext-install zip

# Installing Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Set the working directory to the Laravel app
WORKDIR /var/www/html

# Copying the Laravel app files to the container
COPY laravel-php-app/ .

# Installing Laravel dependencies using Composer
RUN composer install --no-scripts --no-interaction

# Generate the Laravel application key
RUN php artisan key:generate

# Set the document root
ENV APACHE_DOCUMENT_ROOT /mnt/c/akshaya/my-laravel-project/laravel-php-app/public/
RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf

# Enabling Apache modules and restart Apache
RUN a2enmod rewrite && service apache2 restart

# Exposing port 80
EXPOSE 80

# Start Apache in the foreground
CMD ["apache2-foreground"]
