# Using the official MySQL image as a base image
FROM mysql:latest

# Set up environment variables
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=laravel
ENV MYSQL_USER=laravel
ENV MYSQL_PASSWORD=secret

# Expose port 3306
EXPOSE 3306

